# Generated by Django 5.1.1 on 2024-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicinsight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='latitude',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='longitude',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
