# Generated by Django 5.1.1 on 2024-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicinsight', '0002_requestmodel_latitude_requestmodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
